version: '3.9'
services:
  db:
    image: mysql:8.2.0
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - itbook-network

networks:
  itbook-network:
    driver: bridge

volumes:
  mysql-data: