import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Layout from 'antd/es/layout/layout'
import Siderbar from '@/components/dashboard/Siderbar/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout style={{ minHeight: '100vh' }}>
          <Siderbar />
          <Layout>
            {children}
          </Layout>
        </Layout>
      </body>
    </html>
  )
}
