import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Layout from 'antd/es/layout/layout'
import Sider from 'antd/es/layout/Sider'
import BreadcrumbDashBoard from '@/components/dashboard/BreadcrumbDashBoard/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout style={{ minHeight: '100vh'}}>
          <Sider theme={'light'} className='!bg-[#3A4D39]' collapsible>

          </Sider>
          <Layout style={{padding: '10px 15px'}}>
            <BreadcrumbDashBoard />
            {children}
          </Layout>
        </Layout>
      </body>
    </html>
  )
}
